-- File:        update_autogenerated_scripts.sql
-- Location:    musesuperchar/database/misc
-- Project:     Muse Systems Super Characteristics for xTuple ERP
--
-- Licensed to Lima Buttgereit Holdings LLC (d/b/a Muse Systems) under one or
-- more agreements.  Muse Systems licenses this file to you under the Apache
-- License, Version 2.0.
--
-- See the LICENSE file in the project root for license terms and conditions.
-- See the NOTICE file in the project root for copyright ownership information.
--
-- muse.information@musesystems.com  :: https://muse.systems


-- Updates to the package may include fixes and enhancements to the
-- scripts which are automatically created.  As such we should force
-- the re-generation of the various scripts that might have been
-- created since the original installation of the package.  Note that
-- this process may take time.
DO
    $BODY$
        BEGIN
            PERFORM musesuperchar.update_entity_qt_data_metasql_files(entity_id)
                ,musesuperchar.update_entity_qt_data_js_files(entity_id)
            FROM musesuperchar.entity;

            PERFORM musesuperchar.update_scgrp_qt_ui_files(scgrp_id)
            FROM musesuperchar.scgrp;
        END;

    $BODY$;
