/*************************************************************************
 *************************************************************************
 **
 ** File:         update_autogenerated_scripts.sql
 ** Project:      Muse Systems Super Characteristics for xTuple ERP
 ** Author:       Steven C. Buttgereit
 **
 ** (C) 2017-2018 Lima Buttgereit Holdings LLC d/b/a Muse Systems
 **
 ** Contact:
 ** muse.information@musesystems.com  :: https://muse.systems
 **
 ** License: MIT License. See LICENSE.md for complete licensing details.
 **
 *************************************************************************/

-- Updates to the package may include fixes and enhancements to the
-- scripts which are automatically created.  As such we should force
-- the re-generation of the various scripts that might have been
-- created since the original installation of the package.  Note that
-- this process may take time.
DO
    $BODY$
        BEGIN
            PERFORM musesuperchar.update_entity_qt_data_metasql_files(entity_id)
                ,musesuperchar.update_entity_qt_data_js_files(entity_id)
            FROM musesuperchar.entity;

            PERFORM musesuperchar.update_scgrp_qt_ui_files(scgrp_id)
            FROM musesuperchar.scgrp;
        END;

    $BODY$;
