/*************************************************************************
 *************************************************************************
 **
 ** File:         update_scgrp_qt_ui_files.sql
 ** Project:      Muse Systems Super Characteristics for xTuple ERP
 ** Author:       Steven C. Buttgereit
 **
 ** (C) 2017 Lima Buttgereit Holdings LLC d/b/a Muse Systems
 **
 ** Contact:
 ** muse.information@musesystems.com  :: https://muse.systems
 ** 
 ** License: MIT License. See LICENSE.md for complete licensing details.
 **
 *************************************************************************
 ************************************************************************/

--
-- Causes an update of the database generated Qt UI related files to be
-- regenerated and updated in the database.
--

CREATE OR REPLACE FUNCTION musesuperchar.update_scgrp_qt_ui_files(pGroupId bigint) 
    RETURNS void AS
        $BODY$
            DECLARE
                vCfgPfx text := musextputils.get_musemetric('musesuperchar','widgetPrefix',null::text);
                vScGrpIntName text;
                vUiForm xml;
                vUiBackingJs text;
                vUiFormName text;
            BEGIN

                SELECT scgrp_internal_name INTO vScGrpIntName 
                FROM musesuperchar.scgrp
                WHERE scgrp_id = pGroupId;

                IF vScGrpIntName IS NULL THEN
                    RAISE EXCEPTION 'We require a valid Group ID in order to update its Qt UI related files. (FUNC: musesuperchar.update_scgrp_qt_ui_files) (pGroupId: %)',pGroupId;
                END IF;

                ALTER TABLE musesuperchar.pkguiform
                    DISABLE TRIGGER pkguiformaftertrigger;
                ALTER TABLE musesuperchar.pkguiform
                    DISABLE TRIGGER pkguiformaltertrigger;
                ALTER TABLE musesuperchar.pkguiform
                    DISABLE TRIGGER pkguiformbeforetrigger;

                ALTER TABLE musesuperchar.pkgscript
                    DISABLE TRIGGER pkgscriptaftertrigger;
                ALTER TABLE musesuperchar.pkgscript
                    DISABLE TRIGGER pkgscriptaltertrigger;
                ALTER TABLE musesuperchar.pkgscript
                    DISABLE TRIGGER pkgscriptbeforetrigger;

                vUiFormName := vCfgPfx||'_'||vScGrpIntName;

                -- We do different things depending on if we have Group Layout 
                -- Records or not.  If so, we update the layout.  If not, we go
                -- on and delete the related Qt UI related files.
                IF NOT EXISTS (SELECT true
                                FROM musesuperchar.scdef_scgrp_ass 
                                WHERE scdef_scgrp_ass_scgrp_id = pGroupId) THEN
                    DELETE FROM musesuperchar.pkguiform
                        WHERE uiform_name = vUiFormName
                            AND uiform_order = 0;

                    DELETE FROM musesuperchar.pkgscript
                        WHERE script_name = vUiFormName
                            AND script_order = 0;
                ELSE
                    vUiForm := musesuperchar.get_qt_ui_xml(
                        musesuperchar.get_group_layout_structure(pGroupId));
                    vUiBackingJs := musesuperchar.get_qt_form_js(
                        pGroupId, vUiForm);

                    -- Now we either insert or update the files; would love to 
                    -- do INSERT ON CONFLICT, but our required keys are not
                    -- unique indexed :-(
                    -- Start with the UI XML
                    IF NOT EXISTS (SELECT true
                                   FROM musesuperchar.pkguiform
                                   WHERE uiform_name = vUiFormName
                                        AND uiform_order = 0) THEN
                        INSERT INTO musesuperchar.pkguiform 
                            (uiform_name   
                            ,uiform_order  
                            ,uiform_enabled
                            ,uiform_source 
                            ,uiform_notes)
                        VALUES
                            (vUiFormName
                            ,0
                            ,true 
                            ,'<?xml version="1.0" encoding="UTF-8"?>'||vUiForm::text
                            ,'Autogenerated Super Charateristics Form, Last Updated: '||
                                now());
                    ELSE
                        UPDATE   musesuperchar.pkguiform
                           SET   uiform_source = 
                                    '<?xml version="1.0" encoding="UTF-8"?>'||
                                    vUiForm::text
                                ,uiform_notes = 
                                    'Autogenerated Super Charateristics Form, Last Updated: '||
                                    now()
                        WHERE    uiform_name = vUiFormName
                            AND  uiform_order = 0;
                    END IF;

                    -- Now process the UI JS.
                    IF NOT EXISTS (SELECT true
                                   FROM musesuperchar.pkgscript
                                   WHERE script_name = vUiFormName
                                        AND script_order = 0) THEN
                        INSERT INTO musesuperchar.pkgscript 
                            (script_name   
                            ,script_order  
                            ,script_enabled
                            ,script_source 
                            ,script_notes)
                        VALUES
                            (vUiFormName
                            ,0
                            ,true 
                            ,vUiBackingJs
                            ,'Autogenerated Super Charateristics Form Backing Script, Last Updated: '||
                                now());
                    ELSE
                        UPDATE   musesuperchar.pkgscript
                           SET   script_source = vUiBackingJs
                                ,script_notes = 
                                    'Autogenerated Super Charateristics Form Backing Script, Last Updated: '||
                                    now()
                        WHERE    script_name = vUiFormName
                            AND  script_order = 0;
                    END IF;

                END IF;

                ALTER TABLE musesuperchar.pkguiform
                    ENABLE TRIGGER pkguiformaftertrigger;
                ALTER TABLE musesuperchar.pkguiform
                    ENABLE TRIGGER pkguiformaltertrigger;
                ALTER TABLE musesuperchar.pkguiform
                    ENABLE TRIGGER pkguiformbeforetrigger;

                ALTER TABLE musesuperchar.pkgscript
                    ENABLE TRIGGER pkgscriptaftertrigger;
                ALTER TABLE musesuperchar.pkgscript
                    ENABLE TRIGGER pkgscriptaltertrigger;
                ALTER TABLE musesuperchar.pkgscript
                    ENABLE TRIGGER pkgscriptbeforetrigger;

            END;
        $BODY$
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER;

ALTER FUNCTION musesuperchar.update_scgrp_qt_ui_files(pGroupId bigint)
    OWNER TO admin;

REVOKE EXECUTE ON FUNCTION musesuperchar.update_scgrp_qt_ui_files(pGroupId bigint) FROM public;
GRANT EXECUTE ON FUNCTION musesuperchar.update_scgrp_qt_ui_files(pGroupId bigint) TO admin;
GRANT EXECUTE ON FUNCTION musesuperchar.update_scgrp_qt_ui_files(pGroupId bigint) TO xtrole;


COMMENT ON FUNCTION musesuperchar.update_scgrp_qt_ui_files(pGroupId bigint) 
    IS $DOC$Causes an update of the database generated Qt UI related files to be regenerated and updated in the database.$DOC$;
